# Generated by Django 3.0.6 on 2020-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_return',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
